version: '3'
services:
  postgresql:
    container_name: postgres
    image: postgres:13.5
    ports:
     - "5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  app:
    build: .
    volumes:
      - ./rates:/app
    ports:
      - "3000:3000"